### ISSUE TITLE
Clone Base API Automation framework

### ISSUE THREAD

**Issue by AnjarTiyo** [Capstone-Group3-Mentutor/QE-API#7]
Dear @AnjarTiyo @havidn @amalliarizkii @Ilhamsyhs 

Please clone basic API Automation framework at: https://github.com/Capstone-Group3-Mentutor/QE-API.git

Thanks

**Comment by AnjarTiyo** [comment]
Anjar done cloning

**Comment by AnjarTiyo** [comment]
I have customized some feature, so its is not raw anymore

**Comment by havidn** [comment]
Done cloning

**Comment by amalliarizkii** [comment]
Done cloning
